GET http://localhost:4001/

###
POST http://localhost:4001/register/
Content-Type: application/json

{
   "fullname":"charan",
   "email":"cherri657@gamail.com",
   "mobile":7434563337,
   "skills":"node.js",
   "password":"cherri324" ,
   "confirmPassword":"cherri324" 
}

###
POST http://localhost:4001/login 
Content-Type: application/json

{
   "email":"cherri657@gamail.com",
   "password":"cherri324"
}

###
GET http://localhost:4001/alldevelopers
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRiOWU1ZjcxZTkyOWQzNDQ3NjA0ODlmIiwiaWF0IjoxNjkwNzk2MjQzLCJleHAiOjE3MjY3OTYyNDN9.B9CI6QoYhoAJPm8HCz3_OQmuWHkxTRWBUmNbpke35WI

###
GET http://localhost:4001/individualprofile/64b9daf8e0114888264639bd
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRiOWU1ZjcxZTkyOWQzNDQ3NjA0ODlmIiwiaWF0IjoxNjkwNzk2MjQzLCJleHAiOjE3MjY3OTYyNDN9.B9CI6QoYhoAJPm8HCz3_OQmuWHkxTRWBUmNbpke35WI

###
POST http://localhost:4001/addreview/
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRjNzg4ZDMxYjVkZjBmY2Y5ZmE1ZTk4IiwiaWF0IjoxNjkwNzk4MzEyLCJleHAiOjE3MjY3OTgzMTJ9.8Wt3DsG2a0skUhOZAtnFjEwMpdHaWAlg943pjTL4-AI



{
            "taskworker":"janardhan",
            "rating":"4.6"
}
