GET http://localhost:4009/

###
POST http://localhost:4009/register/
Content-Type: application/json

{
   "fullname":"charan",
   "email":"cherri657@gamail.com",
   "mobile":7434563337,
   "skills":"node.js",
   "password":"cherri324" ,
   "confirmPassword":"cherri324" 
}

###
POST http://localhost:4009/login 
Content-Type: application/json

{
   "email":"cherri657@gamail.com",
   "password":"cherri324"
}

###
GET http://localhost:4009/alldevelopers
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRiOWU1ZjcxZTkyOWQzNDQ3NjA0ODlmIiwiaWF0IjoxNjg5OTMwNjgwLCJleHAiOjE3MjU5MzA2ODB9.V1G5h6nt8l8nzwzKAJ8MVQhTjQcLmxWn4WXFCzrenO4

###
GET http://localhost:4009/individualprofile/64b9daf8e0114888264639bd
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRiOWU1ZjcxZTkyOWQzNDQ3NjA0ODlmIiwiaWF0IjoxNjg5OTMwNjgwLCJleHAiOjE3MjU5MzA2ODB9.V1G5h6nt8l8nzwzKAJ8MVQhTjQcLmxWn4WXFCzrenO4

###
POST http://localhost:4009/addreview/
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRiOWU1ZjcxZTkyOWQzNDQ3NjA0ODlmIiwiaWF0IjoxNjg5OTMwNjgwLCJleHAiOjE3MjU5MzA2ODB9.V1G5h6nt8l8nzwzKAJ8MVQhTjQcLmxWn4WXFCzrenO4



{
            "taskworker":"janardhan",
            "rating":"4.6"
}
