GET http://localhost:3002/

###
POST http://localhost:3004/register/
Content-Type: application/json

{
   "fullname":"charan",
   "email":"cherri657@gamail.com",
   "mobile":7434563337,
   "skills":"node.js",
   "password":"cherri324" ,
   "confirmPassword":"cherri324" 
}

###
POST http://localhost:3005/login 
Content-Type: application/json

{
   "email":"cherri657@gamail.com",
   "password":"cherri324"
}

###
GET http://localhost:3006/alldevelopers
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRiOWU1ZjcxZTkyOWQzNDQ3NjA0ODlmIiwiaWF0IjoxNjg5OTMwNjgwLCJleHAiOjE3MjU5MzA2ODB9.V1G5h6nt8l8nzwzKAJ8MVQhTjQcLmxWn4WXFCzrenO4

###
GET http://localhost:3006/individualprofile/64b9d707dbf73c27677ff5ec
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRiOWU1ZjcxZTkyOWQzNDQ3NjA0ODlmIiwiaWF0IjoxNjg5OTMwNjgwLCJleHAiOjE3MjU5MzA2ODB9.V1G5h6nt8l8nzwzKAJ8MVQhTjQcLmxWn4WXFCzrenO4
